- name: varibles from files
  hosts: localhost
  connection: local
  vars_files:
  - varibles-file.yaml
  tasks:
    - name: print varibles 
      ansible.builtin.debug:
        msg: "student {{ name }} {{ branch }} and {{ roll_number }}"

    