- name: install packages
  hosts: frontend
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.packges:
      name: "{{ item }}"
      state: installed
    loop: 
    - mysql
    - nginx
    - zip