- name: install packages
  hosts: frontend
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.packge:
      name: "{{ item }}"
      state: present
    loop: 
    - mysql
    - nginx
    - zip