- name: functions
  hosts: local
  connection: local
  vars:
    persons: "harsha, vardhan, nandigama"
  tasks:
  - name: checking undefined variable
    ansible.builtin.debug:
      msg: "hello {{ person | default('ayyan') }}"

  - name: print names
    ansible.builtin.debug:
      msg: "hello{{ persons | split(',') }}"
  
  - name: covert map to list
    vars:
      course:
        name: ansible
        duaration: 10hrs
        trainer: harsha
    ansible.builtin.debug:
      msg: "course info: {{ course | dict2items  }}"

  - name: check ip address is valid or not
    vars:
      ip: "3oo.338.389.374"
    ansible.builtin.debug:
      msg: "is {{ ip | ansible.utils.ipaddr }}"